### ISSUE TITLE
Exposing ingress service ports on Linux

### ISSUE THREAD

**Issue by bmassemin** [kubernetes-sigs/cloud-provider-kind#107]
I am currently trying the kind solution to set up a local cluster, and also cloud-provider-kind to have a load balancer. If I want to expose the ingress controller on my local network, I need the envoy container port to be mapped to the host, and [according to the code](https://github.com/kubernetes-sigs/cloud-provider-kind/blob/b6c63d059f6a9c7385cfea3ad3634c2faf345594/pkg/loadbalancer/server.go#L226), port mapping is only done if the OS is macOS or Windows or WSL2. 
How can I expose envoy on my local network with docker running on Linux?

**Comment by aojea** [comment]
you better use portmapping and publish the ports in the 0.0.0.0 https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings
