### ISSUE TITLE
Allow 

### ISSUE THREAD

**Issue by vuldin** [kubernetes-sigs/cloud-provider-kind#108]
MetalLB allows setting an annotation `allow-shared-ip` that makes it possible to set the same IP address across two LoadBalancer services. This is helpful specifically for DNS services, since they should be able to use both TCP and UDP protocols:

```
  annotations:
    metallb.universe.tf/allow-shared-ip: "DNS"
```

Is there a way to do this with cloud-provider-kind?

**Comment by aojea** [comment]
you can use TCP and UDP protocol on the same Service, why you should use the same IP on multiple Services?

**Comment by aojea** [comment]
/close

no answer, feel free to reopen if there is some follow up, the limitation on LoadBAlancer services for multiple protocols was removed in 1.26 https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1435-mixed-protocol-lb
