### ISSUE TITLE
feature request: prompt you if you're running on a Mac and not under sudo

### ISSUE THREAD

**Issue by craigbox** [kubernetes-sigs/cloud-provider-kind#117]
I got bitten by https://github.com/kubernetes-sigs/cloud-provider-kind/issues/90.

Could you detect a user running locally on a Mac (not in a container) and terminate if they don't have the permissions to accept network connections?

**Comment by aojea** [comment]
This seems a good first issue , we just need to validate before starts, I would say here after the flag parsing

https://github.com/kubernetes-sigs/cloud-provider-kind/blob/827fdb16eda5d85eb055a7cad9ed2c1a14a415ae/cmd/app.go#L40-L43

if the process has enough privileges

```
	if runtime.GOOS == "darwin" {
		// check if the process has privileges to add ip address to the system
	}
```

the exercise is to figure out how golang can detect if it has the right privileges in mac

**Comment by aojea** [comment]
Fixes by https://github.com/kubernetes-sigs/cloud-provider-kind/pull/128

Thanks @zzzk1
