### ISSUE TITLE
list the images used by cloud-provider-kind so users can mirror them

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/cloud-provider-kind#118]
In the meantime, just providing a tool to list the images should be enough, because the mirror user can mirror those, pull them and locally fix the tags if for some reason they're not going to make them match in the mirror (... I would really like to hear more about why mirroring necessitates altering the tags, but even if it must, you can alter the tag in local storage to fix it for now).

_Originally posted by @BenTheElder in https://github.com/kubernetes-sigs/cloud-provider-kind/issues/110#issuecomment-2294902949_

**Comment by rihib** [comment]
Hello, I would like to work on this issue!

/assign

**Comment by BenTheElder** [comment]
/remove-good-first-issue

@aojea if you had added the label using the /command it would've highlighted the expectations for good first issue, which has requirements like:

> Provides Context If background knowledge is required, this should be explicitly mentioned and a list of suggested readings included.

> Gives Examples Link to examples of similar implementations so new contributors have a reference guide for their changes.

> Identifies Relevant Code The relevant code and tests to be changed should be linked in the issue.


That are not true here.

https://www.kubernetes.dev/docs/guide/help-wanted/

**Comment by sftim** [comment]
Might as well:
/help

**Comment by BenTheElder** [comment]
(as discussed in slack though: anyone is welcome to work on this, however we have high expectations for ourselves when suggesting an issue is "good first issue" to make sure they're well-documented etc)
