### ISSUE TITLE
Fix or reduce frequency or switch off perma-failing jobs 

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/cloud-provider-kind#12]
Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

| CI Job | Days Failed |
| --- | --- |
| ci-kubernetes-cloud-provider-kind-conformance-parallel  |  26 |
| ci-kubernetes-cloud-provider-kind-conformance-parallel-ipv6 |  26 |

Additional Context:
https://github.com/kubernetes/test-infra/issues/18600

**Comment by aojea** [comment]
Thanks for noticing @dims , I have to come back to this problem this week

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-cloud-provider-kind-conformance-parallel-ipv6/1665415520444223488

I have a problem on the installer script

> ================================================================================
> wrapper.sh] [TEST] Running Test Command: `bash -c curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && cd ./../../k8s.io/kubernetes && ./../../sigs.k8s.io/cloud-provider-kind/hack/ci/e2e.sh` ...
> kind
> e2e-k8s.sh
> bash: line 1: ./../../sigs.k8s.io/cloud-provider-kind/hack/ci/e2e.sh: No such file or directory
>

**Comment by aojea** [comment]
Fixed

https://testgrid.k8s.io/sig-testing-kind#cloud-provider-kind%20conformance,%20master%20(dev)%20%5Bnon-serial%5D
https://testgrid.k8s.io/sig-testing-kind#cloud-provider-kind%20(IPv6),%20master%20(dev)%20%5Bnon-serial%5D
