### ISSUE TITLE
Not connecting with podman on macos (podman privileged port bind issue)

### ISSUE THREAD

**Issue by david-martin** [kubernetes-sigs/cloud-provider-kind#146]
```
macos 14.5

podman version
Client:       Podman Engine
Version:      5.2.3
API Version:  5.2.3
Go Version:   go1.23.1
Git Commit:   c5366a308e89edd9636b66faf79bd5cb18ed0905
Built:        Tue Sep 24 16:17:57 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      5.2.5
API Version:  5.2.5
Go Version:   go1.22.7
Built:        Fri Oct 18 01:00:00 2024
OS/Arch:      linux/arm64

kind v0.24.0 go1.21.7 darwin/amd64
```

Note I do have https://github.com/jasonmadigan/podman-mac-net-connect/ installed as well, which is similar to https://github.com/chipmk/docker-mac-net-connect, but for podman. I've used this with metallb before.

Steps to reproduce issue:

```bash
kind create cluster
sudo cloud-provider-kind
kubectl apply -f examples/loadbalancer_etp_local.yaml

kubectl get service lb-service-local
NAME               TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
lb-service-local   LoadBalancer   10.96.200.152   10.89.0.6     80:31477/TCP   5s

curl 10.89.0.6:80/hostname
  (times out)
```

```bash
podman ps
CONTAINER ID  IMAGE                                                                                           COMMAND               CREATED             STATUS             PORTS                                                       NAMES
e3fdebe88bc5  docker.io/kindest/node@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865                        2 minutes ago       Up 2 minutes       127.0.0.1:51765->6443/tcp                                   kind-control-plane
8ef808566cb0  docker.io/envoyproxy/envoy:v1.30.1                                                              bash -c echo -en ...  About a minute ago  Up About a minute  0.0.0.0:34801->80/tcp, 0.0.0.0:34171->10000/tcp, 10000/tcp  kindccm-JQR2TXKKQBRJNYZ4LUJ4TY4C2YAW4FANP7ZCY5PN
```

* cloud-provider-kind logs https://gist.github.com/david-martin/f0050403c968767d574dab3d015d61cc
* kindccm container logs https://gist.github.com/david-martin/66078a10c4b23096a14ff97a625085ce

**Comment by aojea** [comment]
You should not have to use any mac-net-connect thing, cloud-provider-kind enables the 10.89.0.4 address in the host and forwards to the container via the portmaps

```
I1025 16:04:20.941551   30219 tunnel.go:34] found port maps map[10000:34171 80:34801] associated to container kindccm-JQR2TXKKQBRJNYZ4LUJ4TY4C2YAW4FANP7ZCY5PN
I1025 16:04:21.020126   30219 tunnel.go:41] setting IPv4 address 10.89.0.6 associated to container kindccm-JQR2TXKKQBRJNYZ4LUJ4TY4C2YAW4FANP7ZCY5PN
I1025 16:04:21.068858   30219 tunnel.go:112] Starting tunnel on 10.89.0.6:10000
I1025 16:04:21.069025   30219 tunnel.go:112] Starting tunnel on 10.89.0.6:80
```

can you disable those things and try to connect to the 10.89.0.6:80 or 10.89.0.6:10000 that shows in your logs?

**Comment by david-martin** [comment]
@aojea thanks for reaching out.

I stopped podman-mac-net-connect and tried again, but unfortunately seeing the same behaviour.

When I try port 10000, I get this error:

```
curl 10.89.0.6:1000/hostname
curl: (7) Failed to connect to 10.89.0.6 port 1000 after 1 ms: Couldn't connect to server
```

I noticed a couple errors in the kindccm logs https://gist.github.com/david-martin/66078a10c4b23096a14ff97a625085ce#file-podman_kindccm-log-L112-L113 I wonder if that's related to the problem?

**Comment by aojea** [comment]
if you connect to localhost:34171 on your host?

we need to identify the pipe that is broken 😄

**Comment by david-martin** [comment]
I've since torn down and brought up an environment again, so the ips & ports are different. 
Here's some output and behaviour:

```bash
podman ps
CONTAINER ID  IMAGE                                                                                           COMMAND               CREATED        STATUS        PORTS                                                       NAMES
a3a211deba3f  docker.io/kindest/node@sha256:53df588e04085fd41ae12de0c3fe4c72f7013bba32a20e7325357a1ac94ba865                        2 minutes ago  Up 2 minutes  127.0.0.1:61350->6443/tcp                                   kind-control-plane
918e0f3f432a  docker.io/envoyproxy/envoy:v1.30.1                                                              bash -c echo -en ...  3 seconds ago  Up 4 seconds  0.0.0.0:36713->80/tcp, 0.0.0.0:37001->10000/tcp, 10000/tcp  kindccm-JQR2TXKKQBRJNYZ4LUJ4TY4C2YAW4FANP7ZCY5PN
```

```
I1029 09:20:47.425857   90914 tunnel.go:34] found port maps map[10000:37001 80:36713] associated to container kindccm-JQR2TXKKQBRJNYZ4LUJ4TY4C2YAW4FANP7ZCY5PN
I1029 09:20:47.499079   90914 tunnel.go:41] setting IPv4 address 10.89.0.10 associated to container kindccm-JQR2TXKKQBRJNYZ4LUJ4TY4C2YAW4FANP7ZCY5PN
I1029 09:20:47.512287   90914 tunnel.go:112] Starting tunnel on 10.89.0.10:10000
I1029 09:20:47.512474   90914 tunnel.go:112] Starting tunnel on 10.89.0.10:80
```

```bash
curl 10.89.0.10:10000
<!DOCTYPE html>
<html lang='en'>
<head>

  <title>Envoy Admin</title>
...
```

`curl 0.0.0.0:37001` also gives above response

`curl 10.89.0.10:80` hangs/times out

`curl 0.0.0.0:36713` gives `curl: (56) Recv failure: Connection reset by peer`

**Comment by aojea** [comment]
ok, then connect to the envoy container with `podman exec -it ... bash` and from there try to connect to the nodeport on one of the kind containers

**Comment by david-martin** [comment]
I think this means the nodeport can be reached from the envoy container?

```
root@kindccm-JQR2TXKKQBRJNYZ4LUJ4TY4C2YAW4FANP7ZCY5PN:/# cat /home/envoy/cds.yaml |grep -A 4 socket_address
              socket_address:
                address: 10.89.0.9
                port_value: 30992
                protocol: TCP
root@kindccm-JQR2TXKKQBRJNYZ4LUJ4TY4C2YAW4FANP7ZCY5PN:/# bash -c "echo > /dev/tcp/10.89.0.9/30992 && echo 'Open' || echo 'Closed'"
Open
```

If that is the case, the problem is betwen host and the envoy container, but only on port 80, not on port 1000?
Which may be related to these entries in envoy logs
```
podman logs 918e0f3f432a |grep -i error
[2024-10-29 09:20:47.244][6][error][config] [source/common/listener_manager/listener_manager_impl.cc:1186] listener 'listener_IPv4_80_TCP' failed to bind or apply socket options: cannot bind '0.0.0.0:80': Permission denied
[2024-10-29 09:20:47.244][6][warning][config] [source/extensions/config_subscription/filesystem/filesystem_subscription_impl.cc:63] Filesystem config update rejected: Error adding/updating listener(s) listener_IPv4_80_TCP: cannot bind '0.0.0.0:80': Permission denied
```

**Comment by aojea** [comment]
hmm, the containers run as privileged
https://github.com/kubernetes-sigs/cloud-provider-kind/blob/43cbeb6a2847ed416aeca3269d96302058cf9436/pkg/loadbalancer/server.go#L210

can you try the example using high ports for the Service?  > 1024?

We need to discard the problem is with lower ports

**Comment by david-martin** [comment]
8080 works.
Looks like https://github.com/containers/podman/issues/21679
```
kubectl get service lb-service-local
NAME               TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
lb-service-local   LoadBalancer   10.96.159.189   10.89.0.11    8080:32153/TCP   4s

curl 10.89.0.11:8080/hostname
policy-local-77dc66c467-rn57m
```

If I'm understanding the suggestion in that issue correctly, is it possible to pass 0.0.0.0 into the `--publish` option so that it works on macos?
https://github.com/kubernetes-sigs/cloud-provider-kind/blob/43cbeb6a2847ed416aeca3269d96302058cf9436/pkg/loadbalancer/server.go#L234

**Comment by aojea** [comment]
> If I'm understanding the suggestion in that issue correctly, is it possible to pass 0.0.0.0 into the `--publish` option so that it works on macos?

I don't know, you can give it a try `podman run -p0.0.0.0:1023:80`

**Comment by david-martin** [comment]
> I don't know, you can give it a try podman run -p0.0.0.0:1023:80

That works, using `podman run --publish=0.0.0.0:80:8080/TCP jmalloc/echo-server`
Which in turn led me down a path of trying to modify the `--publish` args to explicitly include `0.0.0.0` and rebuild the binary locally.
However, that made no difference. 
The problem is not with the envoy container starting and listening on port 80 on the host.
The problem is when envoy itself tries to start and listen on port 80 inside the container.

The doc at https://github.com/containers/podman/blob/main/rootless.md gives more context

> Podman can not create containers that bind to ports < 1024

As a test, I added this to the args (which feels a little hacky)

```golang
		"--sysctl=net.ipv4.ip_unprivileged_port_start=1", // Allow lower port numbers for podman
```

and it now works

```bash
curl 10.89.0.17/hostname
policy-local-77dc66c467-w74cv
```

**Comment by aojea** [comment]
do you mean that just adding the sysctl is enough, or we need  both the 0.0.0.0 and the sysctl?

**Comment by david-martin** [comment]
> do you mean that just adding the sysctl is enough, or we need both the 0.0.0.0 and the sysctl?

Just adding the sysctl is enough.
The 0.0.0.0 seems to be implied by leaving it out (see output from podman ps before)

> feel free to send a PR and we can discuss there

#152
