### ISSUE TITLE
support Cluster Autoscaler (CA) testing

### ISSUE THREAD

**Issue by pohly** [kubernetes-sigs/cloud-provider-kind#16]
I am working on Kubernetes and Cluster Autoscaler (CA) master. For testing beyond unit tests, I need a cluster which runs a locally built Kubernetes and that is supported by CA when I run CA (either automatically or under a debugger).

I want to do this primarily on a Linux workstation where I have Docker installed. It might also be useful to support this in a Prow job.

**Comment by pohly** [comment]
It could be that https://cluster-api.sigs.k8s.io/user/quick-start is already supporting this. I need to check.

I am under the impression that the Cluster API can be implemented by cloud providers, so perhaps it can be implemented by cloud-provider-kind such that the Cluster API backend in CA works?

**Comment by BenTheElder** [comment]
> I am under the impression that the Cluster API can be implemented by cloud providers, so perhaps it can be implemented by cloud-provider-kind such that the Cluster API backend in CA works?

Different overloading of the term "cloud provider"

"cloud-provider-kind" is a provider in the Kubernetes component sense. Cluster API is referring to cloud providers in the sense of "AWS, GCP".

Auto-scaling is going to be out of scope for this component. cc @aojea we should probably link back to the slack thread
