### ISSUE TITLE
flaky image builds

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/cloud-provider-kind#171]
https://testgrid.k8s.io/sig-testing-kind#post-cloud-provider-kind-image

**Comment by aojea** [comment]
> Your build timed out. Use the [--timeout=DURATION] flag to change the timeout threshold.

how can it take more than one hour https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/post-cloud-provider-kind-image

the good one takes 5 mins

**Comment by stmcginnis** [comment]
Unfortunately it doesn't have timestamps for most of it, but some areas that could cause delays that come to mind:

- Throttling during pulling docker image layers
- Resource contention on the build host slowing down the process
- Throttling during pulling go packages for the build

We could probably add some explicit timestamp logging to help narrow down what areas are taking so long. Just trying to brainstorm ideas.

**Comment by BenTheElder** [comment]
or qemu flakes? we are compiling under emulation instead of cross compiling, we should fix that. it will be faster and more reliable.

**Comment by BenTheElder** [comment]
I'll send a cross-compile PR for the docker image ...

**Comment by BenTheElder** [comment]
the push job is substantially faster now after https://github.com/kubernetes-sigs/cloud-provider-kind/pull/173 as expected, reliably under 3m.

**Comment by BenTheElder** [comment]
previously ~5m-9m with the occasionally 1h+ hang:
https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/post-cloud-provider-kind-image 

I'm going to presume this is closed for now and reopen it later if we get another alert for flakes
