### ISSUE TITLE
Add Discussions

### ISSUE THREAD

**Issue by johnmanko** [kubernetes-sigs/cloud-provider-kind#172]
I have a few questions, but don't want to clutter Issues with them.  Can you create a "Discussion" section.  The Slack channel is only for approved participants, so I can't connect.

**Comment by BenTheElder** [comment]
slack is open-invite at https://slack.k8s.io and the kind channel (and nearly all channels) are public and unrestricted

**Comment by johnmanko** [comment]
Hmm, I didnt know of that.  I tried doing a direct slack invite, like other communities, but wasnt available.  Thanks.

**Comment by BenTheElder** [comment]
> I tried doing a direct slack invite, like other communities, but wasn't available. Thanks.

Yeah, we have > 200,000 users in the Kubernetes slack, so it's only done via automation where possible, we should add the join link to the docs.

**Comment by BenTheElder** [comment]
in the kind repo we link to both slack.k8s.io and the channel https://github.com/kubernetes-sigs/kind#community
