### ISSUE TITLE
Connection refuse when trying to connect to the load balancer IP

### ISSUE THREAD

**Issue by tanvp112** [kubernetes-sigs/cloud-provider-kind#34]
Hi,

I followed exactly the steps outlined in `README.md` and couldn't connect to the service from my host. I noticed when I did `kubectl get service/lb-service-local`, the `EXTERNAL-IP` reported is an IP from the docker bridge CIDR (172.x.x.x). Should I be getting my host IP instead? Anyway, curl to the 172.x.x.x failed with connection timeout. If I docker exec into any of the kind worker, i can curl the external IP without issue.

Is it this provider only works within the docker CIDR or am I missing anything on the README? Does this has anything to do with the kindest/haproxy container run by this provider on the host?

Thanks.

**Comment by aojea** [comment]
> Is it this provider only works within the docker CIDR or am I missing anything on the README?

right now only works when you are connected to the docker bridge, but we are trying to extend this to more platforms but we need feedback, can you explain better how is your setup? are you using windows or mac? is your docker network in a different hosts?

**Comment by tanvp112** [comment]
My dev machine is a Fedora with docker installed, all the test done on this local machine. I think the haproxy should run on both host (to accept traffic from host network) and bridge (reverse proxy to service in the kind cluster) network. I am not sure what is the haproxy currently doing. Any idea?

**Comment by aojea** [comment]
The docker bridge is reachable from the host, no need to run on the host network.
Some possibility is that your machine is filtering those packets, it will be good to understand your setup, Fedora has known issues about problems between firewalld and the docker network, so try to validate that firewalld is not the one blocking your packets https://discussion.fedoraproject.org/t/docker-causing-errors-in-firewall-startup/93920/5

If that is not the problem we'll need more information from your environment
`kubectl get service (name of the service) -o yaml`
`docker network inspect kind`
`iptables-save`

**Comment by tanvp112** [comment]
It's not the firewall. I will have to put this aside first. Perhaps a more detail documentation of the haproxy could help in the future.

Many thanks for your prompt replies, appreciated!

**Comment by aojea** [comment]
>  Perhaps a more detail documentation of the haproxy could help in the future.

haproxy is a container that listens in a specific port, you just need to be able to connect to that container in the port where the service is exposed, there is no much magic there

**Comment by tanvp112** [comment]
> need to be able to connect to that container in the port where the service is exposed

Not much use if the exposed haproxy port is not accessible on the host network, thus suggested above the haproxy spawn by this provider should also run on host network.

**Comment by aojea** [comment]
> Not much use if the exposed haproxy port is not accessible on the host network

it is accessible in the host network, the docker network belongs to the host network same as the haproxy IPs
