### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by gary-archer** [kubernetes-sigs/cloud-provider-kind#44]
So far [this issue](https://github.com/kubernetes-sigs/cloud-provider-kind/issues/41) added macOS support to get External IPs. That update did all of the difficult work, so this request is just to support Windows equivalently.

### Why are we solving this issue?

To enable people to run real-world deployments on a development computer and better rehearse production deployments. For example at my company I provide OAuth code examples where a web client might connect to Kubernetes deployed API endpoints to enable an end-to-end solution. We would like this to work for Linux, macOS and Windows host computers without developer specific deployment logic that can cause confusion. I think the change requested is fully aligned with the goals of this project.

### To address this issue, are there any code changes? If there are code changes, what needs to be done in the code and what places can the assignee treat as reference points?

The main code changes have been made already by @aojea and this is just to fill in a missing command that he was unsure about since he did not have access to a Windows computer.

### Does this issue have zero to low barrier of entry?

Yes.

### How can the assignee reach out to you for help?

Yes - if required.

**Comment by aojea** [comment]
> The code currently I throws a not implemented error, 

we just need the command that allows to add an IP to an interface in windows

https://github.com/kubernetes-sigs/cloud-provider-kind/blob/fa5e2fcf963a0d16e8ed5e3aa10308723b08378e/pkg/loadbalancer/address_windows.go#L7-L12


the information I found so far is https://stackoverflow.com/questions/8944860/how-to-create-an-ip-alias-on-windows

but that name sounds arbitrary, ideally will be to use a loopback interface , but the comments seems to indicate people has to do some manual steps to enable it

**Comment by gary-archer** [comment]
Cool - I will do some investigation when I get some time, later in April.

**Comment by gary-archer** [comment]
Sorry - been a bit snowed under recently but I finally got a bit of spare time debugging this and you were right - it works equivalently on Windows as on macOS:

I updated [address_windows.go](https://github.com/gary-archer/cloud-provider-kind/blob/main/pkg/loadbalancer/address_windows.go) in a fork of your project. In my tracing I received values like these:

```markdown
ifaceName=lo0
ip=172.19.0.3
```

This translates to commands of this form, yet the `lo0` interface does not exist on Windows so these commands fail:

```bash
netsh interface ip add address lo0 172.19.0.3 255.255.255.255
netsh interface ip delete address lo0 172.19.0.3 255.255.255.255
```

If I therefore used the Windows interface name of `loopback` and updated the code like this and it worked fine:

```go
//go:build windows

package loadbalancer

import (
	"os/exec"
)

func AddIPToInterface(ifaceName string, ip string) error {
	// The passed through ifaceName is 'lo0' which is called 'loopback' on Windows
	err := exec.Command("netsh", "interface", "ip", "add", "address", "loopback", ip, "255.255.255.255").Run()
	if err != nil {
		return err
	}
	return nil
}

func RemoveIPToInterface(ifaceName string, ip string) error {
	// The passed through ifaceName is 'lo0' which is called 'loopback' on Windows
	err := exec.Command("netsh", "interface", "ip", "delete", "address", "loopback", ip, "255.255.255.255").Run()
	if err != nil {
		return err
	}
	return nil
}
```

In my setup I used `Run as Administrator` to run a Git Bash shell, which is a Windows equivalent of using `sudo`.

**Comment by gary-archer** [comment]
So my thoughts are to integrate this change in your preferred way and update the README something like this:

```markdown
- Mainly tested with docker and Linux.
- On macOS you must run cloud-provider-kind with sudo
- On Windows you must run cloud-provider-kind from a shell started with the 'Run as administrator' option
- We welcome further feedback from podman, Windows and Mac users
```

**Comment by aojea** [comment]
@gary-archer those changes look good to me, just submit a PR with them

```diff
diff --git a/pkg/loadbalancer/address_windows.go b/pkg/loadbalancer/address_windows.go
index fd686e0..b0d0e8e 100644
--- a/pkg/loadbalancer/address_windows.go
+++ b/pkg/loadbalancer/address_windows.go
@@ -2,12 +2,24 @@
 
 package loadbalancer
 
-import "fmt"
+import (
+       "os/exec"
+)
 
 func AddIPToInterface(ifaceName string, ip string) error {
-       return fmt.Errorf(("not implemented"))
+       // The passed through ifaceName is 'lo0' which is called 'loopback' on Windows
+       err := exec.Command("netsh", "interface", "ip", "add", "address", "loopback", ip, "255.255.255.255").Run()
+       if err != nil {
+               return err
+       }
+       return nil
 }
 
 func RemoveIPToInterface(ifaceName string, ip string) error {
-       return fmt.Errorf(("not implemented"))
+       // The passed through ifaceName is 'lo0' which is called 'loopback' on Windows
+       err := exec.Command("netsh", "interface", "ip", "delete", "address", "loopback", ip, "255.255.255.255").Run()
+       if err != nil {
+               return err
+       }
+       return nil
 }
```

**Comment by aojea** [comment]
Fixed by https://github.com/kubernetes-sigs/cloud-provider-kind/pull/49
