### ISSUE TITLE
Any cast ip

### ISSUE THREAD

**Issue by antgubarev** [kubernetes-sigs/cloud-provider-kind#50]
On the node there is an anycast IP address (10.0.5.5). However, the cloud provider provides another IP address for the load balancer, which is physically located on the node. How can I set up an anycast?

**Comment by aojea** [comment]
> On the node there is an anycast IP address (10.0.5.5). However, the cloud provider provides another IP address for the load balancer, which is physically located on the node. How can I set up an anycast?

This projects tries to emulate a cloud provider and the provisioning of the load balancers, for complex network setups you can use other projects https://mauilion.dev/posts/kind-metallb/. or create your own kind network plugins https://github.com/aojea/kind-networking-plugins

Thanks
