### ISSUE TITLE
Toggle to publish to fixed port

### ISSUE THREAD

**Issue by wtzhang23** [kubernetes-sigs/cloud-provider-kind#59]
Environment: Docker for Mac

I was wondering if a flag can be added to fix the port exposed on the host instead of selecting randomly (`--publish-all`). For example, a flag that simply uses the service's port in [this](https://github.com/kubernetes-sigs/cloud-provider-kind/blob/main/pkg/loadbalancer/server.go#L199-L207) section of code. My understanding is that it is currently random in the situation where multiple LoadBalancer services exist on the same port? 
This would be useful in my case as I'm using a single ingress (istio) on a single kind server node that is schedulable and would like a deterministic way to call it from the host. If this sounds like a good idea, this sounds like an easy PR I can whip up.

**Comment by aojea** [comment]
> This would be useful in my case as I'm using a single ingress (istio) on a single kind server node that is schedulable and would like a deterministic way to call it from the host. If this sounds like a good idea, this sounds like an easy PR I can whip up.

> NAME               TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
> lb-service-local   LoadBalancer   10.96.207.137   192.168.8.7   80:31215/TCP   57s

It is already deterministic, you connect to the externalIP and Port , in the example above `192.168.8.7:80`

**Comment by wtzhang23** [comment]
I'll need to read the code a bit more, but is the IP deterministic as well? As in can you fetch it without asking for it from the k8s api server?

**Comment by aojea** [comment]
have you tried the examples?

**Comment by wtzhang23** [comment]
Oh probably should have done that. I went straight in to using it. I guess it is possible and I can close this.

**Comment by wtzhang23** [comment]
Ran some more tests and found it to be consistent. In case anyone else stumbles on this thread:
* The external ip is guaranteed to be in the "kind" network or whatever is passed into `KIND_EXPERIMENTAL_DOCKER_NETWORK` subnet
* In the case if only one kind cluster is in the network, the ip is consistent (.1 is host gateway, .2 is node1, ..., then the next available ip gets selected for the container that does the proxying between external ip and the load balancer)

Though for my case, it is probably better to just kubectl get the external ip and write it to a file to be consumed by other dependencies.
