### ISSUE TITLE
Loadbalancer IP does not work with cilium 

### ISSUE THREAD

**Issue by nitang22** [kubernetes-sigs/cloud-provider-kind#65]
Hi,
I have a very unique use case here. The loadbalancer IP does not working with Cilium as CNI using `kubeProxyReplacement=true` as shown in those setup [here](https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/) and [here](https://docs.cilium.io/en/stable/network/servicemesh/ingress/). It works using kube-proxy. 

I can't pinpoint exactly the issue but I get a connection reset by peer. Seems like it can reach the ip but cannot reach the envoy proxy in cilium

![image](https://github.com/kubernetes-sigs/cloud-provider-kind/assets/163345923/4b76baf6-7107-44c2-b6d9-4837846ef108)

[cloud-provider-kind.log](https://github.com/kubernetes-sigs/cloud-provider-kind/files/15221599/cloud-provider-kind.log)

Tried the same setup on AKS, works fine.

**Comment by aojea** [comment]
Interesting , have you tried to connect to the nodePort in one of the nodes and see if that works? (30929 in your example)

**Comment by aojea** [comment]
No answer, so I'll close it, feel free to reopen if you can provide more information

**Comment by nitang22** [comment]
nodePort works, it comes from the integration between kind and cloud-provider-kind

**Comment by aojea** [comment]
> nodePort works, it comes from the integration between kind and cloud-provider-kind. Can't reopen the issue on my side, can you do it? @aojea

/reopen

absolutely

It is interesting it fails since the packet that arrives to the node comes proxied from the container and is directed to the nodeport ... maybe some cilium config about nodeports that is not liking that flow? but that will be a non-standard behavior most likely

**Comment by nitang22** [comment]
That's the tricky part, couldn't test on other emulator like minikube since it does not support deactivating the kubeproxy. On Azure, it works. I will try to test on other emulator as well.

**Comment by danwinship** [comment]
Random guess: Cilium is probably assuming that since the `LoadBalancerStatus` has an `IP` rather than a `Hostname`, that that means it's using VIP-mode load balancing like GCE rather than Proxy-mode load balancing like AWS. Which is to say, Cilium probably hasn't been updated for [KEP-1860](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1860-kube-proxy-IP-node-binding) yet. (Despite the low KEP number, this is actually a recent feature.)

**Comment by baurmatt** [comment]
For reference: This has been implemented https://github.com/cilium/cilium/pull/34780 and seems to be released with the next Cilium release (1.17.0)
